# print("How old are you?.",)
# age = input()
# print("How tall are you?",)
# height=input()
# print("How much do you weught?",)
# weight = input()

# print("So, you are %r old, %r tall and %r heavy." %(age, height, weight))
print("How are you Aqeel?")
mood = input()
print("How's  weather today?")
weather = input()
print(" So you are having a %s day with %s view outside window" %(mood, weather))